repos:
- repo: https://github.com/semgrep/pre-commit
  rev: 'v1.131.0'
  hooks:
    - id: semgrep
      entry: semgrep
      args: ["--config", "p/secrets", "--config", "p/comment"]
      verbose: true